# Kuberang GitLab CI Config
before_script:
  - export VERSION=$(git describe --tags --always --dirty)
  - mkdir -p /go/src/github.com/apprenda/kuberang
  - ln -s /builds/kismatic/kuberang /go/src/github.com/apprenda/kuberang
  - cd /go/src/github.com/apprenda/kuberang

stages:
  - package
  - upload

build:
  image: golang:1.8
  stage: package
  script:
    - make build

s3-upload:
  image: cgswong/aws:aws
  stage: upload
  script:
    - aws s3 cp bin/linux/amd64/kuberang s3://kismatic-installer/kuberang/$VERSION/kuberang-linux-amd64 --acl public-read --region us-east-1
    - aws s3 cp bin/darwin/amd64/kuberang s3://kismatic-installer/kuberang/$VERSION/kuberang-darwin-amd64 --acl public-read --region us-east-1
    - aws s3 cp bin/linux/amd64/kuberang s3://kismatic-installer/kuberang/latest/kuberang-linux-amd64 --acl public-read --region us-east-1
    - aws s3 cp bin/darwin/amd64/kuberang s3://kismatic-installer/kuberang/latest/kuberang-darwin-amd64 --acl public-read --region us-east-1
